## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: funqyhttptrigger      # set this to your function app name on Azure
  POM_XML_DIRECTORY: '.'                     # set this to the directory which contains pom.xml file
  POM_FUNCTIONAPP_NAME: funqy-azure-example        # set this to the function app name in your local development environment
  JAVA_VERSION: '1.17.x'                      # set this to the java version to use


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub action'
        uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: maven

      - name: 'Build'
        run: ./mvnw clean package -DskipTests -Dnative

      - name: Archive the function zip
        uses: actions/upload-artifact@v3
        with:
          name: function-zip
          path: /target/funqy-azure-example.zip

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      -  name: Deploy to Azure
         uses: Azure/functions-action@v1
         with:
            app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
            package: '${{ env.POM_XML_DIRECTORY }}/target/${{ env.POM_FUNCTIONAPP_NAME }}.zip'
